Ext.define('Estratificacion.store.consulta.LadoManzana',{
	extend:'Ext.data.Store',
	model:'Estratificacion.model.consulta.LadoManzana',
	fields:['gid','lado_manz','cod_manzana','estrato'],
	autoLoad:false,
	proxy:{
		type:'ajax',
		reader:{
			type:'json',
			root:'data'
		}
	}
});